version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-dev-bch-node_www_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  init:
    image: alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    entrypoint: >-
      /bin/sh -c '
        apk add --no-cache envsubst &&
        if [ ! -f /data/node/bitcoin.conf ]; then
          mkdir -p /data/node &&
          envsubst < /templates/bitcoin.conf.template > /data/node/bitcoin.conf &&
          chown -R 1000:1000 /data/node
        fi
      '
    volumes:
      - ${APP_DATA_DIR}/data:/data
      - ${APP_DATA_DIR}/data/templates:/templates:ro
    environment:
      RPC_USER: "bch"
      RPC_PASSWORD: "${APP_PASSWORD}"
      APPS_SUBNET: "${NETWORK_IP}/16"
      BCH_P2P_PORT: "28333"
      BCH_RPC_PORT: "28332"
      BCH_ZMQ_HASHBLOCK_PORT: "28334"

  bchn:
    image: mainnet/bitcoin-cash-node:v28.0.1
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 15m30s
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "28333:28333/tcp" # P2P
      - "28332:28332/tcp" # RPC
      - "28334:28334/tcp" # ZMQ (hashblock)
    volumes:
      - ${APP_DATA_DIR}/data/node:/data
    entrypoint:
      - bitcoind
    command:
      - -datadir=/data
      - -printtoconsole

  www:
    image: halverneus/static-file-server:v1.8.11@sha256:2e91ce7ffb8519eeb882ba52d75c191ca6c921c16438447362128ef73ee2ea7e
    user: "1000:1000"
    environment:
      - FOLDER=/www
      - PORT=80
    volumes:
      - ${APP_DATA_DIR}/data/www:/www:ro
    restart: on-failure

