version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-dev-axebench_server_1
      APP_PORT: 5050

  server:
    image: ghcr.io/willitmod/axebench-release:v3.0.2-r1@sha256:bbd179793fed078717223f8a9906445fe08cceaa98c34248fc61ef5983cf6c61
    restart: on-failure
    stop_grace_period: 30s
    init: true
    environment:
      AXE_HOST: 0.0.0.0
      AXE_PORT: 5050
      HOME: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data
